#!/usr/bin/env node
// Copies the compiled MetrxCore ABI into packages/shared and, when a deployment
// record exists, patches the checked-in address constants. Run after
// `pnpm contracts:build` and after every mainnet deploy.

import {readFileSync, writeFileSync, existsSync} from "node:fs";
import {fileURLToPath} from "node:url";
import {dirname, join} from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const artifact = join(root, "contracts/out/MetrxCore.sol/MetrxCore.json");
const abiOut = join(root, "packages/shared/src/abi/metrxCore.ts");
const addressesOut = join(root, "packages/shared/src/addresses.ts");
const deploymentFile = join(root, "deployments/botchain-mainnet.json");

if (!existsSync(artifact)) {
  console.error("No compiled artifact. Run `pnpm contracts:build` first.");
  process.exit(1);
}

const {abi} = JSON.parse(readFileSync(artifact, "utf8"));
writeFileSync(
  abiOut,
  `// Generated by scripts/sync-abi.mjs from contracts/out/MetrxCore.sol/MetrxCore.json.\n` +
    `// Do not edit by hand.\n\n` +
    `export const metrxCoreAbi = ${JSON.stringify(abi, null, 2)} as const;\n`
);
console.log(`abi   -> packages/shared/src/abi/metrxCore.ts (${abi.length} entries)`);

const EXPECTED_CHAIN_ID = 677;

if (existsSync(deploymentFile)) {
  const d = JSON.parse(readFileSync(deploymentFile, "utf8"));

  // A local or testnet run must never be able to write itself into the mainnet address
  // constants the web app and worker ship with.
  if (Number(d.chainId) !== EXPECTED_CHAIN_ID) {
    console.error(
      `addr  -> REFUSED: ${deploymentFile} records chain ${d.chainId}, not BOT Chain Mainnet (${EXPECTED_CHAIN_ID}).\n` +
        `         Delete it before syncing, or deploy against $BOT_RPC_URL.`
    );
    process.exit(1);
  }

  // A forge script cannot know its own transaction hash, so recover it from the broadcast log.
  const broadcast = join(root, `contracts/broadcast/Deploy.s.sol/${d.chainId}/run-latest.json`);
  if (existsSync(broadcast)) {
    const run = JSON.parse(readFileSync(broadcast, "utf8"));
    const create = run.transactions?.find(
      (t) => t.contractAddress?.toLowerCase() === d.metrxCore.toLowerCase()
    );
    if (create?.hash) d.deployTxHash = create.hash;
    const receipt = run.receipts?.find((r) => r.transactionHash === create?.hash);
    if (receipt?.blockNumber) d.deployedAtBlock = Number(BigInt(receipt.blockNumber));
    writeFileSync(deploymentFile, `${JSON.stringify(d, null, 2)}\n`);
  }

  let src = readFileSync(addressesOut, "utf8");
  const patch = (key, value, quoted = true) => {
    const replacement = quoted ? `${key}: "${value}",` : `${key}: ${value},`;
    src = src.replace(new RegExp(`  ${key}: .*,`), `  ${replacement}`);
  };
  patch("metrxCore", d.metrxCore);
  patch("aiVerifier", d.aiVerifier);
  patch("deployedAtBlock", d.deployedAtBlock ?? 0, false);
  patch("deployTxHash", d.deployTxHash ?? "");
  patch("verifiedOnExplorer", d.verifiedOnExplorer === true, false);
  writeFileSync(addressesOut, src);
  console.log(`addr  -> packages/shared/src/addresses.ts (metrxCore ${d.metrxCore})`);
} else {
  console.log("addr  -> skipped, no deployments/botchain-mainnet.json yet");
}
